const defaultLangs = [
  {
    id: "abap",
    scopeName: "source.abap",
    path: "/languages/abap.tmLanguage.json",
    samplepath: "/languages/abap.sample",
  },
  {
    id: "actionscript-3",
    scopeName: "source.actionscript.3",
    path: "/languages/actionscript-3.tmLanguage.json",
    samplepath: "/languages/actionscript-3.sample",
  },
  {
    id: "ada",
    scopeName: "source.ada",
    path: "/languages/ada.tmLanguage.json",
    samplepath: "/languages/ada.sample",
  },
  {
    id: "apache",
    scopeName: "source.apacheconf",
    path: "/languages/apache.tmLanguage.json",
  },
  {
    id: "apex",
    scopeName: "source.apex",
    path: "/languages/apex.tmLanguage.json",
    samplepath: "/languages/apex.sample",
  },
  {
    id: "apl",
    scopeName: "source.apl",
    path: "/languages/apl.tmLanguage.json",
    embeddedLangs: ["html", "xml", "css", "javascript", "json"],
  },
  {
    id: "applescript",
    scopeName: "source.applescript",
    path: "/languages/applescript.tmLanguage.json",
    samplepath: "/languages/applescript.sample",
  },
  {
    id: "asm",
    scopeName: "source.asm.x86_64",
    path: "/languages/asm.tmLanguage.json",
    samplepath: "/languages/asm.sample",
  },
  {
    id: "astro",
    scopeName: "text.html.astro",
    path: "/languages/astro.tmLanguage.json",
    samplepath: "/languages/astro.sample",
    embeddedLangs: ["css", "sass", "scss", "tsx"],
  },
  {
    id: "awk",
    scopeName: "source.awk",
    path: "/languages/awk.tmLanguage.json",
    samplepath: "/languages/awk.sample",
  },
  {
    id: "ballerina",
    scopeName: "source.ballerina",
    path: "/languages/ballerina.tmLanguage.json",
    samplepath: "/languages/ballerina.sample",
  },
  {
    id: "bat",
    scopeName: "source.batchfile",
    path: "/languages/bat.tmLanguage.json",
    samplepath: "/languages/bat.sample",
    aliases: ["batch"],
  },
  {
    id: "c",
    scopeName: "source.c",
    path: "/languages/c.tmLanguage.json",
    samplepath: "/languages/c.sample",
  },
  {
    id: "clojure",
    scopeName: "source.clojure",
    path: "/languages/clojure.tmLanguage.json",
    samplepath: "/languages/clojure.sample",
    aliases: ["clj"],
  },
  {
    id: "cobol",
    scopeName: "source.cobol",
    path: "/languages/cobol.tmLanguage.json",
    samplepath: "/languages/cobol.sample",
    embeddedLangs: ["sql", "html", "java"],
  },
  {
    id: "codeql",
    scopeName: "source.ql",
    path: "/languages/codeql.tmLanguage.json",
    samplepath: "/languages/codeql.sample",
    aliases: ["ql"],
  },
  {
    id: "coffee",
    scopeName: "source.coffee",
    path: "/languages/coffee.tmLanguage.json",
    samplepath: "/languages/coffee.sample",
    embeddedLangs: ["javascript"],
  },
  {
    id: "cpp",
    scopeName: "source.cpp",
    path: "/languages/cpp.tmLanguage.json",
    samplepath: "/languages/cpp.sample",
    embeddedLangs: ["sql"],
  },
  {
    id: "crystal",
    scopeName: "source.crystal",
    path: "/languages/crystal.tmLanguage.json",
    samplepath: "/languages/crystal.sample",
    embeddedLangs: ["html", "sql", "css", "c", "javascript", "shellscript"],
  },
  {
    id: "csharp",
    scopeName: "source.cs",
    path: "/languages/csharp.tmLanguage.json",
    samplepath: "/languages/csharp.sample",
    aliases: ["c#"],
  },
  {
    id: "css",
    scopeName: "source.css",
    path: "/languages/css.tmLanguage.json",
    samplepath: "/languages/css.sample",
  },
  {
    id: "d",
    scopeName: "source.d",
    path: "/languages/d.tmLanguage.json",
    samplepath: "/languages/d.sample",
  },
  {
    id: "dart",
    scopeName: "source.dart",
    path: "/languages/dart.tmLanguage.json",
    samplepath: "/languages/dart.sample",
  },
  {
    id: "diff",
    scopeName: "source.diff",
    path: "/languages/diff.tmLanguage.json",
    samplepath: "/languages/diff.sample",
  },
  {
    id: "docker",
    scopeName: "source.dockerfile",
    path: "/languages/docker.tmLanguage.json",
    samplepath: "/languages/docker.sample",
  },
  {
    id: "dream-maker",
    scopeName: "source.dm",
    path: "/languages/dream-maker.tmLanguage.json",
  },
  {
    id: "elixir",
    scopeName: "source.elixir",
    path: "/languages/elixir.tmLanguage.json",
    samplepath: "/languages/elixir.sample",
    embeddedLangs: ["html"],
  },
  {
    id: "elm",
    scopeName: "source.elm",
    path: "/languages/elm.tmLanguage.json",
    samplepath: "/languages/elm.sample",
  },
  {
    id: "erb",
    scopeName: "text.html.erb",
    path: "/languages/erb.tmLanguage.json",
    samplepath: "/languages/erb.sample",
    embeddedLangs: ["html", "ruby"],
  },
  {
    id: "erlang",
    scopeName: "source.erlang",
    path: "/languages/erlang.tmLanguage.json",
    samplepath: "/languages/erlang.sample",
  },
  {
    id: "fish",
    scopeName: "source.fish",
    path: "/languages/fish.tmLanguage.json",
    samplepath: "/languages/fish.sample",
  },
  {
    id: "fsharp",
    scopeName: "source.fsharp",
    path: "/languages/fsharp.tmLanguage.json",
    samplepath: "/languages/fsharp.sample",
    aliases: ["f#"],
    embeddedLangs: ["markdown"],
  },
  {
    id: "gherkin",
    scopeName: "text.gherkin.feature",
    path: "/languages/gherkin.tmLanguage.json",
  },
  {
    id: "git-commit",
    scopeName: "text.git-commit",
    path: "/languages/git-commit.tmLanguage.json",
    embeddedLangs: ["diff"],
  },
  {
    id: "git-rebase",
    scopeName: "text.git-rebase",
    path: "/languages/git-rebase.tmLanguage.json",
    embeddedLangs: ["shellscript"],
  },
  {
    id: "gnuplot",
    scopeName: "source.gnuplot",
    path: "/languages/gnuplot.tmLanguage.json",
  },
  {
    id: "go",
    scopeName: "source.go",
    path: "/languages/go.tmLanguage.json",
    samplepath: "/languages/go.sample",
  },
  {
    id: "graphql",
    scopeName: "source.graphql",
    path: "/languages/graphql.tmLanguage.json",
    embeddedLangs: ["javascript", "typescript", "jsx", "tsx"],
  },
  {
    id: "groovy",
    scopeName: "source.groovy",
    path: "/languages/groovy.tmLanguage.json",
  },
  {
    id: "hack",
    scopeName: "source.hack",
    path: "/languages/hack.tmLanguage.json",
    embeddedLangs: ["html", "sql"],
  },
  {
    id: "haml",
    scopeName: "text.haml",
    path: "/languages/haml.tmLanguage.json",
    embeddedLangs: ["ruby", "javascript", "sass", "coffee", "markdown", "css"],
  },
  {
    id: "handlebars",
    scopeName: "text.html.handlebars",
    path: "/languages/handlebars.tmLanguage.json",
    aliases: ["hbs"],
    embeddedLangs: ["html", "css", "javascript", "yaml"],
  },
  {
    id: "haskell",
    scopeName: "source.haskell",
    path: "/languages/haskell.tmLanguage.json",
  },
  {
    id: "hcl",
    scopeName: "source.hcl",
    path: "/languages/hcl.tmLanguage.json",
  },
  {
    id: "hlsl",
    scopeName: "source.hlsl",
    path: "/languages/hlsl.tmLanguage.json",
  },
  {
    id: "html",
    scopeName: "text.html.basic",
    path: "/languages/html.tmLanguage.json",
    samplepath: "/languages/html.sample",
    embeddedLangs: ["javascript", "css"],
  },
  {
    id: "ini",
    scopeName: "source.ini",
    path: "/languages/ini.tmLanguage.json",
  },
  {
    id: "java",
    scopeName: "source.java",
    path: "/languages/java.tmLanguage.json",
    samplepath: "/languages/java.sample",
  },
  {
    id: "javascript",
    scopeName: "source.js",
    path: "/languages/javascript.tmLanguage.json",
    samplepath: "/languages/javascript.sample",
    aliases: ["js"],
  },
  {
    id: "jinja-html",
    scopeName: "text.html.jinja",
    path: "/languages/jinja-html.tmLanguage.json",
    embeddedLangs: ["html"],
  },
  {
    id: "json",
    scopeName: "source.json",
    path: "/languages/json.tmLanguage.json",
  },
  {
    id: "jsonc",
    scopeName: "source.json.comments",
    path: "/languages/jsonc.tmLanguage.json",
  },
  {
    id: "jsonnet",
    scopeName: "source.jsonnet",
    path: "/languages/jsonnet.tmLanguage.json",
  },
  {
    id: "jssm",
    scopeName: "source.jssm",
    path: "/languages/jssm.tmLanguage.json",
    samplepath: "/languages/jssm.sample",
    aliases: ["fsl"],
  },
  {
    id: "jsx",
    scopeName: "source.js.jsx",
    path: "/languages/jsx.tmLanguage.json",
  },
  {
    id: "julia",
    scopeName: "source.julia",
    path: "/languages/julia.tmLanguage.json",
    embeddedLangs: ["cpp", "python", "javascript", "r", "sql"],
  },
  {
    id: "jupyter",
    scopeName: "source.jupyter",
    path: "/languages/jupyter.tmLanguage.json",
    embeddedLangs: ["json"],
  },
  {
    id: "kotlin",
    scopeName: "source.kotlin",
    path: "/languages/kotlin.tmLanguage.json",
  },
  {
    id: "latex",
    scopeName: "text.tex.latex",
    path: "/languages/latex.tmLanguage.json",
    embeddedLangs: [
      "tex",
      "css",
      "html",
      "java",
      "javascript",
      "typescript",
      "lua",
      "python",
      "julia",
      "ruby",
      "xml",
      "yaml",
      "cpp",
      "haskell",
      "scala",
      "gnuplot",
    ],
  },
  {
    id: "less",
    scopeName: "source.css.less",
    path: "/languages/less.tmLanguage.json",
    embeddedLangs: ["css"],
  },
  {
    id: "lisp",
    scopeName: "source.lisp",
    path: "/languages/lisp.tmLanguage.json",
  },
  {
    id: "logo",
    scopeName: "source.logo",
    path: "/languages/logo.tmLanguage.json",
  },
  {
    id: "lua",
    scopeName: "source.lua",
    path: "/languages/lua.tmLanguage.json",
    embeddedLangs: ["c"],
  },
  {
    id: "make",
    scopeName: "source.makefile",
    path: "/languages/make.tmLanguage.json",
    aliases: ["makefile"],
  },
  {
    id: "markdown",
    scopeName: "text.html.markdown",
    path: "/languages/markdown.tmLanguage.json",
    aliases: ["md"],
    embeddedLangs: [
      "css",
      "html",
      "ini",
      "java",
      "lua",
      "make",
      "perl",
      "r",
      "ruby",
      "php",
      "sql",
      "vb",
      "xml",
      "xsl",
      "yaml",
      "bat",
      "clojure",
      "coffee",
      "c",
      "cpp",
      "diff",
      "docker",
      "git-commit",
      "git-rebase",
      "go",
      "groovy",
      "pug",
      "javascript",
      "json",
      "jsonc",
      "less",
      "objective-c",
      "swift",
      "scss",
      "raku",
      "powershell",
      "python",
      "rust",
      "scala",
      "shellscript",
      "typescript",
      "tsx",
      "csharp",
      "fsharp",
      "dart",
      "handlebars",
      "erlang",
      "elixir",
      "latex",
    ],
  },
  {
    id: "matlab",
    scopeName: "source.matlab",
    path: "/languages/matlab.tmLanguage.json",
  },
  {
    id: "mdx",
    scopeName: "text.html.markdown.jsx",
    path: "/languages/mdx.tmLanguage.json",
    embeddedLangs: ["jsx", "markdown"],
  },
  {
    id: "nginx",
    scopeName: "source.nginx",
    path: "/languages/nginx.tmLanguage.json",
  },
  {
    id: "nim",
    scopeName: "source.nim",
    path: "/languages/nim.tmLanguage.json",
    embeddedLangs: ["c", "html", "xml", "javascript", "css", "markdown"],
  },
  {
    id: "nix",
    scopeName: "source.nix",
    path: "/languages/nix.tmLanguage.json",
  },
  {
    id: "objective-c",
    scopeName: "source.objc",
    path: "/languages/objective-c.tmLanguage.json",
    aliases: ["objc"],
  },
  {
    id: "objective-cpp",
    scopeName: "source.objcpp",
    path: "/languages/objective-cpp.tmLanguage.json",
  },
  {
    id: "ocaml",
    scopeName: "source.ocaml",
    path: "/languages/ocaml.tmLanguage.json",
  },
  {
    id: "pascal",
    scopeName: "source.pascal",
    path: "/languages/pascal.tmLanguage.json",
  },
  {
    id: "perl",
    scopeName: "source.perl",
    path: "/languages/perl.tmLanguage.json",
    embeddedLangs: ["html", "xml", "css", "javascript", "sql"],
  },
  {
    id: "php",
    scopeName: "source.php",
    path: "/languages/php.tmLanguage.json",
    embeddedLangs: ["html", "xml", "sql", "javascript", "json", "css"],
  },
  {
    id: "plsql",
    scopeName: "source.plsql.oracle",
    path: "/languages/plsql.tmLanguage.json",
  },
  {
    id: "postcss",
    scopeName: "source.css.postcss",
    path: "/languages/postcss.tmLanguage.json",
  },
  {
    id: "powershell",
    scopeName: "source.powershell",
    path: "/languages/powershell.tmLanguage.json",
    aliases: ["ps", "ps1"],
  },
  {
    id: "prisma",
    scopeName: "source.prisma",
    path: "/languages/prisma.tmLanguage.json",
    samplepath: "/languages/prisma.sample",
  },
  {
    id: "prolog",
    scopeName: "source.prolog",
    path: "/languages/prolog.tmLanguage.json",
  },
  {
    id: "pug",
    scopeName: "text.pug",
    path: "/languages/pug.tmLanguage.json",
    aliases: ["jade"],
    embeddedLangs: ["javascript", "css", "sass", "stylus", "coffee", "html"],
  },
  {
    id: "puppet",
    scopeName: "source.puppet",
    path: "/languages/puppet.tmLanguage.json",
  },
  {
    id: "purescript",
    scopeName: "source.purescript",
    path: "/languages/purescript.tmLanguage.json",
  },
  {
    id: "python",
    scopeName: "source.python",
    path: "/languages/python.tmLanguage.json",
    samplepath: "/languages/python.sample",
    aliases: ["py"],
  },
  {
    id: "r",
    scopeName: "source.r",
    path: "/languages/r.tmLanguage.json",
  },
  {
    id: "raku",
    scopeName: "source.perl.6",
    path: "/languages/raku.tmLanguage.json",
    aliases: ["perl6"],
  },
  {
    id: "razor",
    scopeName: "text.aspnetcorerazor",
    path: "/languages/razor.tmLanguage.json",
    embeddedLangs: ["html", "csharp"],
  },
  {
    id: "riscv",
    scopeName: "source.riscv",
    path: "/languages/riscv.tmLanguage.json",
  },
  {
    id: "ruby",
    scopeName: "source.ruby",
    path: "/languages/ruby.tmLanguage.json",
    samplepath: "/languages/ruby.sample",
    aliases: ["rb"],
    embeddedLangs: [
      "html",
      "xml",
      "sql",
      "css",
      "c",
      "javascript",
      "shellscript",
      "lua",
    ],
  },
  {
    id: "rust",
    scopeName: "source.rust",
    path: "/languages/rust.tmLanguage.json",
  },
  {
    id: "sas",
    scopeName: "source.sas",
    path: "/languages/sas.tmLanguage.json",
    embeddedLangs: ["sql"],
  },
  {
    id: "sass",
    scopeName: "source.sass",
    path: "/languages/sass.tmLanguage.json",
  },
  {
    id: "scala",
    scopeName: "source.scala",
    path: "/languages/scala.tmLanguage.json",
  },
  {
    id: "scheme",
    scopeName: "source.scheme",
    path: "/languages/scheme.tmLanguage.json",
  },
  {
    id: "scss",
    scopeName: "source.css.scss",
    path: "/languages/scss.tmLanguage.json",
    embeddedLangs: ["css"],
  },
  {
    id: "shaderlab",
    scopeName: "source.shaderlab",
    path: "/languages/shaderlab.tmLanguage.json",
    aliases: ["shader"],
    embeddedLangs: ["hlsl"],
  },
  {
    id: "shellscript",
    scopeName: "source.shell",
    path: "/languages/shellscript.tmLanguage.json",
    aliases: ["shell", "bash", "sh", "zsh"],
    embeddedLangs: ["ruby", "python", "applescript", "html", "markdown"],
  },
  {
    id: "smalltalk",
    scopeName: "source.smalltalk",
    path: "/languages/smalltalk.tmLanguage.json",
  },
  {
    id: "solidity",
    scopeName: "source.solidity",
    path: "/languages/solidity.tmLanguage.json",
  },
  {
    id: "sparql",
    scopeName: "source.sparql",
    path: "/languages/sparql.tmLanguage.json",
    samplepath: "/languages/sparql.sample",
    embeddedLangs: ["turtle"],
  },
  {
    id: "sql",
    scopeName: "source.sql",
    path: "/languages/sql.tmLanguage.json",
  },
  {
    id: "ssh-config",
    scopeName: "source.ssh-config",
    path: "/languages/ssh-config.tmLanguage.json",
  },
  {
    id: "stylus",
    scopeName: "source.stylus",
    path: "/languages/stylus.tmLanguage.json",
    aliases: ["styl"],
  },
  {
    id: "svelte",
    scopeName: "source.svelte",
    path: "/languages/svelte.tmLanguage.json",
    embeddedLangs: [
      "javascript",
      "typescript",
      "coffee",
      "stylus",
      "sass",
      "css",
      "scss",
      "less",
      "postcss",
      "pug",
      "markdown",
    ],
  },
  {
    id: "swift",
    scopeName: "source.swift",
    path: "/languages/swift.tmLanguage.json",
  },
  {
    id: "system-verilog",
    scopeName: "source.systemverilog",
    path: "/languages/system-verilog.tmLanguage.json",
  },
  {
    id: "tasl",
    scopeName: "source.tasl",
    path: "/languages/tasl.tmLanguage.json",
    samplepath: "/languages/tasl.sample",
  },
  {
    id: "tcl",
    scopeName: "source.tcl",
    path: "/languages/tcl.tmLanguage.json",
  },
  {
    id: "tex",
    scopeName: "text.tex",
    path: "/languages/tex.tmLanguage.json",
    embeddedLangs: ["r"],
  },
  {
    id: "toml",
    scopeName: "source.toml",
    path: "/languages/toml.tmLanguage.json",
  },
  {
    id: "tsx",
    scopeName: "source.tsx",
    path: "/languages/tsx.tmLanguage.json",
    samplepath: "/languages/tsx.sample",
  },
  {
    id: "turtle",
    scopeName: "source.turtle",
    path: "/languages/turtle.tmLanguage.json",
    samplepath: "/languages/turtle.sample",
  },
  {
    id: "twig",
    scopeName: "text.html.twig",
    path: "/languages/twig.tmLanguage.json",
    embeddedLangs: ["css", "javascript", "php", "python", "ruby"],
  },
  {
    id: "typescript",
    scopeName: "source.ts",
    path: "/languages/typescript.tmLanguage.json",
    aliases: ["ts"],
  },
  {
    id: "vb",
    scopeName: "source.asp.vb.net",
    path: "/languages/vb.tmLanguage.json",
    aliases: ["cmd"],
  },
  {
    id: "verilog",
    scopeName: "source.verilog",
    path: "/languages/verilog.tmLanguage.json",
  },
  {
    id: "vhdl",
    scopeName: "source.vhdl",
    path: "/languages/vhdl.tmLanguage.json",
  },
  {
    id: "viml",
    scopeName: "source.viml",
    path: "/languages/viml.tmLanguage.json",
  },
  {
    id: "vue-html",
    scopeName: "text.html.vue-html",
    path: "/languages/vue-html.tmLanguage.json",
    embeddedLangs: ["vue", "javascript"],
  },
  {
    id: "vue",
    scopeName: "source.vue",
    path: "/languages/vue.tmLanguage.json",
    embeddedLangs: [
      "json",
      "markdown",
      "pug",
      "haml",
      "vue-html",
      "sass",
      "scss",
      "less",
      "stylus",
      "postcss",
      "css",
      "typescript",
      "coffee",
      "javascript",
    ],
  },
  {
    id: "wasm",
    scopeName: "source.wat",
    path: "/languages/wasm.tmLanguage.json",
  },
  {
    id: "wenyan",
    scopeName: "source.wenyan",
    path: "/languages/wenyan.tmLanguage.json",
    aliases: ["文言"],
  },
  {
    id: "xml",
    scopeName: "text.xml",
    path: "/languages/xml.tmLanguage.json",
    embeddedLangs: ["java"],
  },
  {
    id: "xsl",
    scopeName: "text.xml.xsl",
    path: "/languages/xsl.tmLanguage.json",
    embeddedLangs: ["xml"],
  },
  {
    id: "yaml",
    scopeName: "source.yaml",
    path: "/languages/yaml.tmLanguage.json",
  },
];

export default defaultLangs;
